[package]
name = "strawberry-daemon"
version = "0.3.0"
edition = "2021"

[dependencies]
strawberry-core = { path = "../strawberry-core" }
arboard = "3.4"
notify-rust = "4"
serde_json = "1"
wl-clipboard-rs = "0.9"
rusqlite = { version = "0.32", features = ["bundled"] }
ureq = { version = "2", features = ["json"] }
image = "0.25"

[dev-dependencies]

[profile.release]
opt-level = 3
lto = true
